config/routes.rb
Rails.application.routes.draw do
  resources :sectors
  

  resources :pitches
  root 'home#index'
  
  get 'home/about'
  get 'home/consumer'
  get 'home/energy'
  get 'home/finance'
  get 'home/health'
  get 'home/industrials'
  get 'home/medtel'
  get 'home/technology'
  get 'home/utilities'

end

app/models/pitch.rb
class Pitch < ActiveRecord::Base
    scope :like, -> (args) { where("pitch_name like '%#{args}%' OR author like '%#{args}%' OR company_name like '%#{args}%' OR sector_name like '%#{args}%' OR subsector_name like '%#{args}%'")} 
    mount_uploader :document, DocumentUploader
end

app/models/sector.rb
class Sector < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def consumer
    @pitches = Pitch.where(:sector_name => 'Consumer')
  end
  
  def energy
    @pitches = Pitch.where(:sector_name => 'Energy')
  end
  
  def finance
    @pitches = Pitch.where(:sector_name => 'Finance')
  end
  
  def health
    @pitches = Pitch.where(:sector_name => 'Healthcare')
  end
  
  def industrials
    @pitches = Pitch.where(:sector_name => 'Industrial')
  end
  
  def medtel
    @pitches = Pitch.where(:sector_name => 'Medtel')
  end
  
  def technology
    @pitches = Pitch.where(:sector_name => 'Technology')
  end
  
  def utilities
    @pitches = Pitch.where(:sector_name => 'Utilities')
  end
end

app/controllers/pitches_controller.rb
class PitchesController < ApplicationController
  include SmartListing::Helper::ControllerExtensions
  helper  SmartListing::Helper
  before_action :set_pitch, only: [:show, :edit, :update, :destroy]

  # GET /pitches
  # GET /pitches.json
  def index
    pitches_scope = Pitch.order(:pitch_name)
    pitches_scope = pitches_scope.like(params[:filter]) if params[:filter]
    @pitches = smart_listing_create(:pitches, pitches_scope, partial: "pitches/pitch" )
  end

  # GET /pitches/1
  # GET /pitches/1.json
  def show
  end

  # GET /pitches/new
  def new
    @pitch = Pitch.new
  end

  # GET /pitches/1/edit
  def edit
  end

  # POST /pitches
  # POST /pitches.json
  def create
    @pitch = Pitch.new(pitch_params)

    respond_to do |format|
      if @pitch.save
        format.html { redirect_to @pitch, notice: 'Pitch was successfully created.' }
        format.json { render :show, status: :created, location: @pitch }
      else
        format.html { render :new }
        format.json { render json: @pitch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pitches/1
  # PATCH/PUT /pitches/1.json
  def update
    respond_to do |format|
      if @pitch.update(pitch_params)
        format.html { redirect_to @pitch, notice: 'Pitch was successfully updated.' }
        format.json { render :show, status: :ok, location: @pitch }
      else
        format.html { render :edit }
        format.json { render json: @pitch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pitches/1
  # DELETE /pitches/1.json
  def destroy
    @pitch.destroy
    respond_to do |format|
      format.html { redirect_to pitches_url, notice: 'Pitch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pitch
      @pitch = Pitch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pitch_params
      params.require(:pitch).permit(:pitch_name, :pitch_date, :author, :company_name, :sector_name, :subsector_name, :document)
    end
end

app/controllers/sectors_controller.rb
class SectorsController < ApplicationController
  before_action :set_sector, only: [:show, :edit, :update, :destroy]

  # GET /sectors
  # GET /sectors.json
  def index
    @sectors = Sector.all
  end

  # GET /sectors/1
  # GET /sectors/1.json
  def show
    #@pitches = Pitch.order(:pitch_name).where(:sector_name => :sector_name)
  end

  # GET /sectors/new
  def new
    @sector = Sector.new
  end

  # GET /sectors/1/edit
  def edit
  end

  # POST /sectors
  # POST /sectors.json
  def create
    @sector = Sector.new(sector_params)

    respond_to do |format|
      if @sector.save
        format.html { redirect_to @sector, notice: 'Sector was successfully created.' }
        format.json { render :show, status: :created, location: @sector }
      else
        format.html { render :new }
        format.json { render json: @sector.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sectors/1
  # PATCH/PUT /sectors/1.json
  def update
    respond_to do |format|
      if @sector.update(sector_params)
        format.html { redirect_to @sector, notice: 'Sector was successfully updated.' }
        format.json { render :show, status: :ok, location: @sector }
      else
        format.html { render :edit }
        format.json { render json: @sector.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sectors/1
  # DELETE /sectors/1.json
  def destroy
    @sector.destroy
    respond_to do |format|
      format.html { redirect_to sectors_url, notice: 'Sector was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sector
      @sector = Sector.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sector_params
      params.require(:sector).permit(:sector_name, :sector_analysis, :subsector_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pitches_helper.rb
module PitchesHelper
end

app/helpers/sectors_helper.rb
module SectorsHelper
end

app/views/home/about.html.erb
<!--All Industries Index-->
      
    <div class="content">
        <div class="container-fluid"> 
      
      
     
     <!---  <%= image_tag("green-finance.gif", :size => "1100x275") %>  ---> 
     <img src="http://res.cloudinary.com/dop68xspe/image/upload/v1492139220/fina_xzvhqs.jpg"  style="width: 100%;max-height: 100%" />
    
       
        <center><h1>Howard University Investment Group Research Database</h1> 
        
      </center>
        
         <div class="col-md-4">
                        <div class="card card-user">
                            <div class="image">
                                <img src="http://res.cloudinary.com/dop68xspe/image/upload/v1492136583/fina_cubvzk.jpg" alt="..."/>
                            </div>
                            <div class="content">
                                <div class="author">
                                     <a href="#">
                                    <img class="avatar border-gray" src="http://res.cloudinary.com/dop68xspe/image/upload/v1492134902/AAEAAQAAAAAAAAykAAAAJDhkZDdhZDc1LTdiMTktNDdmNy1hYmJjLTBlOWRiZWE1OGY5OQ_q4k4wn.jpg" alt="..."/>

                                      <h4 class="title">Kandice Smith</h4>
                                    </a> 
                                    <p class="description text-center"><br>
                                                    Kandice is a Junior Finance major from Trinidad & Tobago. <br>
                                                    She joined Investment Group in 2015 as a research analyst in the Energy sector.<br>
                                                    In 2017, she will be working as a summer intern at Chicago Fundamental Investment Partners
                                                    She now serves as a portfolio manager for the Investment Group.

                                </p>
                                </div>
                                
                            </div>
                            <hr>
                            <div class="text-center">
                                <button href="#" class="btn btn-simple"><i class="fa fa-facebook-square"></i></button>
                                <button href="#" class="btn btn-simple"><i class="fa fa-twitter"></i></button>
                                <button href="#" class="btn btn-simple"><i class="fa fa-google-plus-square"></i></button>

                            </div>
                        </div>
                    </div> 
                    
                     <div class="col-md-4">
                        <div class="card card-user">
                            <div class="image">
                                <img src="http://res.cloudinary.com/dop68xspe/image/upload/v1492136996/finann_js4e4c.jpg" alt="..."/>
                            </div>
                            <div class="content">
                                <div class="author">
                                     <a href="#">
                                    <img class="avatar border-gray" src="http://res.cloudinary.com/dop68xspe/image/upload/v1492134902/AAEAAQAAAAAAAAmJAAAAJGI4NGQxMDhjLTIwMWEtNDhhNy1hZmY3LTI2ZWJhNGE2NjA4Mg_pfi65b.jpg" alt="..."/>

                                      <h4 class="title">Carlis Robinson<br />
                                      </h4>
                                    </a>
                                    <p class="description text-center"> <br> Carlis is a junior Finance Major from the Bahamas.
                                    He joined Investment Group in 2015 as a research analyst in the Consumer/Retail sector.
                                    In 2017, he will be working at Deutsche Bank in the Investment Banking Department.
                                    He now serves as a portfolio manager for the Investment Group <br><br>

                                </p>
                                </div>
                                
                            </div>
                            <hr>
                            <div class="text-center">
                                <button href="#" class="btn btn-simple"><i class="fa fa-facebook-square"></i></button>
                                <button href="#" class="btn btn-simple"><i class="fa fa-twitter"></i></button>
                                <button href="#" class="btn btn-simple"><i class="fa fa-google-plus-square"></i></button>

                            </div>
                        </div>
                    </div> 
                    
                     <div class="col-md-4">
                        <div class="card card-user">
                            <div class="image">
                                <img src="http://res.cloudinary.com/dop68xspe/image/upload/v1492136875/fina2_pdrdcm.jpg" alt="..."/>
                            </div>
                            <div class="content">
                                <div class="author">
                                     <a href="#">
                                    <img class="avatar border-gray" src="http://res.cloudinary.com/dop68xspe/image/upload/v1492134902/AAEAAQAAAAAAAAzlAAAAJGEwZGIyYTQ0LTUzZjMtNGI2NS1hZjBlLTIxZDY5NDllMjExOA_drpdj1.jpg" alt="..."/>

                                      <h4 class="title">Ronelle Green</h4>
                                      </h4>
                                    </a>
                                    <p class="description text-center"><br> Ronelle is a Junior International Business major from Jamaica
                                    She joined Investment Group in 2016 as a research analyst in the Consumer/Retail sector.
                                    In 2017, she will be working as a summer intern at FTI Consulting. She
                                    now serves as portfolio manager for the Investment Group<br><br>
                                </p>
                                </div>
                                
                            </div>
                            <hr>
                            <div class="text-center">
                                <button href="#" class="btn btn-simple"><i class="fa fa-facebook-square"></i></button>
                                <button href="#" class="btn btn-simple"><i class="fa fa-twitter"></i></button>
                                <button href="#" class="btn btn-simple"><i class="fa fa-google-plus-square"></i></button>

                            </div>
                        </div>
                    </div>
                    
                    
                    
                    
        </div> 
        
        
        
        
        
        
    </div>

app/views/home/consumer.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Pitch name</th>
      <th>Pitch Date</th>
      <th>Author</th>
      <th>Company name</th>
      <th>Sector name</th>
      <th>Subsector name</th>
      <th>Download</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pitches.each do |pitch| %>
      <tr>
        <td><%= link_to pitch.pitch_name, pitch %></td>
        <td><%= pitch.pitch_date %></td>
        <td><%= pitch.author %></td>
        <td><%= pitch.company_name %></td>
        <td><%= pitch.sector_name %></td>
        <td><%= pitch.subsector_name %></td>
        
        <td><%= link_to 'Show', pitch %></td>
        <td><%= link_to 'Edit', edit_pitch_path(pitch) %></td>
        <td><%= link_to 'Delete', pitch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr> 
    <% end %>
   </table> 

app/views/home/energy.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Pitch name</th>
      <th>Pitch Date</th>
      <th>Author</th>
      <th>Company name</th>
      <th>Sector name</th>
      <th>Subsector name</th>
      <th>Download</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pitches.each do |pitch| %>
      <tr>
        <td><%= link_to pitch.pitch_name, pitch %></td>
        <td><%= pitch.pitch_date %></td>
        <td><%= pitch.author %></td>
        <td><%= pitch.company_name %></td>
        <td><%= pitch.sector_name %></td>
        <td><%= pitch.subsector_name %></td>
        <td><%= link_to 'Show', pitch %></td>
        <td><%= link_to 'Edit', edit_pitch_path(pitch) %></td>
        <td><%= link_to 'Delete', pitch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr> 
    <% end %>
   </table> 

app/views/home/finance.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Pitch name</th>
      <th>Pitch Date</th>
      <th>Author</th>
      <th>Company name</th>
      <th>Sector name</th>
      <th>Subsector name</th>
      <th>Download</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pitches.each do |pitch| %>
      <tr>
        <td><%= link_to pitch.pitch_name, pitch %></td>
        <td><%= pitch.pitch_date %></td>
        <td><%= pitch.author %></td>
        <td><%= pitch.company_name %></td>
        <td><%= pitch.sector_name %></td>
        <td><%= pitch.subsector_name %></td>
        <td><%= link_to 'Show', pitch %></td>
        <td><%= link_to 'Edit', edit_pitch_path(pitch) %></td>
        <td><%= link_to 'Delete', pitch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr> 
    <% end %>
  </tbody>
</table> 

app/views/home/health.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Pitch name</th>
      <th>Pitch Date</th>
      <th>Author</th>
      <th>Company name</th>
      <th>Sector name</th>
      <th>Subsector name</th>
      <th>Download</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pitches.each do |pitch| %>
      <tr>
        <td><%= link_to pitch.pitch_name, pitch %></td>
        <td><%= pitch.pitch_date %></td>
        <td><%= pitch.author %></td>
        <td><%= pitch.company_name %></td>
        <td><%= pitch.sector_name %></td>
        <td><%= pitch.subsector_name %></td>
        <td><%= link_to 'Show', pitch %></td>
        <td><%= link_to 'Edit', edit_pitch_path(pitch) %></td>
        <td><%= link_to 'Delete', pitch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr> 
    <% end %>
   </table> 

app/views/home/industrials.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Pitch name</th>
      <th>Pitch Date</th>
      <th>Author</th>
      <th>Company name</th>
      <th>Sector name</th>
      <th>Subsector name</th>
      <th>Download</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pitches.each do |pitch| %>
      <tr>
        <td><%= link_to pitch.pitch_name, pitch %></td>
        <td><%= pitch.pitch_date %></td>
        <td><%= pitch.author %></td>
        <td><%= pitch.company_name %></td>
        <td><%= pitch.sector_name %></td>
        <td><%= pitch.subsector_name %></td>
        <td><%= link_to 'Show', pitch %></td>
        <td><%= link_to 'Edit', edit_pitch_path(pitch) %></td>
        <td><%= link_to 'Delete', pitch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr> 
    <% end %>
   </table> 

app/views/home/medtel.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Pitch name</th>
      <th>Pitch Date</th>
      <th>Author</th>
      <th>Company name</th>
      <th>Sector name</th>
      <th>Subsector name</th>
      <th>Download</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pitches.each do |pitch| %>
      <tr>
        <td><%= link_to pitch.pitch_name, pitch %></td>
        <td><%= pitch.pitch_date %></td>
        <td><%= pitch.author %></td>
        <td><%= pitch.company_name %></td>
        <td><%= pitch.sector_name %></td>
        <td><%= pitch.subsector_name %></td>
        <td><%= link_to 'Show', pitch %></td>
        <td><%= link_to 'Edit', edit_pitch_path(pitch) %></td>
        <td><%= link_to 'Delete', pitch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr> 
    <% end %>
   </table> 

app/views/home/technology.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Pitch name</th>
      <th>Pitch Date</th>
      <th>Author</th>
      <th>Company name</th>
      <th>Sector name</th>
      <th>Subsector name</th>
      <th>Download</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pitches.each do |pitch| %>
      <tr>
        <td><%= link_to pitch.pitch_name, pitch %></td>
        <td><%= pitch.pitch_date %></td>
        <td><%= pitch.author %></td>
        <td><%= pitch.company_name %></td>
        <td><%= pitch.sector_name %></td>
        <td><%= pitch.subsector_name %></td>
        <td><%= link_to 'Show', pitch %></td>
        <td><%= link_to 'Edit', edit_pitch_path(pitch) %></td>
        <td><%= link_to 'Delete', pitch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr> 
    <% end %>
   </table> 
 

app/views/home/utilities.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Pitch name</th>
      <th>Pitch Date</th>
      <th>Author</th>
      <th>Company name</th>
      <th>Sector name</th>
      <th>Subsector name</th>
      <th>Download</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pitches.each do |pitch| %>
      <tr>
        <td><%= link_to pitch.pitch_name, pitch %></td>
        <td><%= pitch.pitch_date %></td>
        <td><%= pitch.author %></td>
        <td><%= pitch.company_name %></td>
        <td><%= pitch.sector_name %></td>
        <td><%= pitch.subsector_name %></td>
        <td><%= link_to 'Show', pitch %></td>
        <td><%= link_to 'Edit', edit_pitch_path(pitch) %></td>
        <td><%= link_to 'Delete', pitch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr> 
    <% end %>
   </table> 

app/views/layouts/_footer.html.erb
        <footer class="footer">
            <div class="container-fluid">
                <nav class="pull-left">
                   <!-- <ul>
                        <li>
                            <a href="#">
                                Home
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Company
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Portfolio
                            </a>
                        </li>
                        <li>
                            <a href="#">
                               Blog
                            </a>
                        </li>
                    </ul>-->
                </nav>
                <p class="copyright pull-right">
                    &copy; 2017 Howard University Investment Group
                </p>
            </div>
        </footer>

    </div>
</div>

app/views/layouts/_sidebar.html.erb
<div class="wrapper">
	<div class="sidebar" data-color="blue" data-image="http://res.cloudinary.com/dop68xspe/image/upload/v1490041566/side_ln9lur.gif" onerror=this.src="http://res.cloudinary.com/dop68xspe/image/upload/v1492147108/ny_l0h1w4.jpg" >
		<!--

        Tip 1: you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple"
        Tip 2: you can also add an image using data-image tag

    -->
		<div class="sidebar-wrapper">
			<div class="logo">
				<center>
					<h6>Investment Group</h6>
				</center>
			</div>
			<ul class="nav">
				<!-- Dropdown Template -->
					
				<li>
				
				<%= link_to home_about_path do %>
				    <i aria-hidden="true" class="fa fa-address-book"></i> About
				<% end %>
				</li> 
				
				<!--- Needs Attentions Causing Application to fails--> 
				<li>
				<%= link_to pitches_path do %>
				    <i aria-hidden="true" class="fa fa-id-card"></i> All Pitches
				<% end %>
				</li> 
				
				
				
					
				<li>
				<%= link_to new_pitch_path do %>
				<i aria-hidden="true" class="fa fa-plus-circle"></i> Upload a New Pitch
				<% end %>
				</li>
				<li>
					<a href="/"><i aria-hidden="true" class="fa fa-circle-o-notch"></i>
					<p>View All Sectors</p></a>
				</li>
				
				<li>
					<a data-toggle="collapse" href="#pagesExamples"><i aria-hidden="true" class="fa fa-plus-circle"></i>
					<p><strong>Select Sector</strong> <b class="caret"></b></p>
					<div class="collapse" id="pagesExamples">
						<ul class="nav">
							
							<li style="list-style: none">
							<li>	
								<%= link_to home_consumer_path do %>
								<i aria-hidden="true" class="fa fa-users"></i>Consumers
								<% end %>
							</li>
							<li>
								<%= link_to home_energy_path do %>
								<i aria-hidden="true" class="fa fa-plug"></i>Energy
								<% end %>
							</li>
							<li>
								<%= link_to home_finance_path do %>
								<i aria-hidden="true" class="fa fa-money"></i>Finance
								<% end %>
							</li>
						
							<li>
								<%= link_to home_health_path do %>
								<i aria-hidden="true" class="fa fa-heart-o"></i>Health
								<% end %>
							</li>
							
							<li>
								<%= link_to home_industrials_path do %>
								<i aria-hidden="true" class="fa fa-flask"></i>Industrials
								<% end %>
							</li>
							<li>
								<%= link_to home_medtel_path do %>
								<i aria-hidden="true" class="fa fa-television"></i>MedTel
								<% end %>
							</li>
								<li>
									<%= link_to home_technology_path do %>
									<i aria-hidden="true" class="fa fa-laptop"></i>Technology
									<% end %>
								</li>
							<li>
								<%= link_to  home_utilities_path do %>
								<i aria-hidden="true" class="fa fa-bolt"></i>Utilities
								<% end %>
							</li>
						</ul>
					</div>
				</li>
			
				
			</ul><!-- Dropwdown Tempalte End -->
		</div>
		</div>

app/views/pitches/_pitch.html.erb
	<p id="notice"><%= notice %></p>
	<div class="card">
					<div class="header">
						<h4 class="title">Pitches</h4>
						<p class="category">This table contains the pitches for every sector</p>
					</div><!---   <div class="content table-responsive table-full-width"> -->
            <div class="row">
            			<div class="col-md-12">
            <div class="conten">
            	<div class="container-fluid">
			<%= smart_listing_controls_for(:pitches, {class: "form-inline text-right"}) do %>
		<div class="f">
			<%= text_field_tag :filter, '', class: "search", placeholder: "Search results here", autocomplete: "on" %>
		</div>
		<% end %>
					<table class="table table-hover table-striped">
						<thead>
							<tr>
								<th>Pitch name</th>
								<th>Pitch Date</th>
								<th>Author</th>
								<th>Company name</th>
								<th>Sector name</th>
								<th>Subsector name</th>
								<th colspan="6"></th>
							</tr>
						</thead>
						<tbody>
							<%unless smart_listing.empty? %><%smart_listing.collection.each do |pitch| %>
							<tr>
								<td><%= link_to pitch.pitch_name, pitch %></td>
								<td><%= pitch.pitch_date %></td>
								<td><%= pitch.author %></td>
								<td><%= pitch.company_name %></td>
								<td><%= pitch.sector_name %></td>
								<td><%= pitch.subsector_name %></td>
								<td><%= link_to 'Show', pitch %></td>
								<td><%= link_to 'Edit', edit_pitch_path(pitch) %></td>
								<td><%= link_to 'Destroy', pitch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
							</tr><%end %>
						</tbody>
					</table> 
			
				<%= link_to 'New Pitch', new_pitch_path, class:"btn btn-info btn-fill pull-left"  %> 
					</div><%= smart_listing.paginate %><%= smart_listing.pagination_per_page_links %><%else %>
				<p class="warning">No records!</p><%end %><br>
			 </div> 
			 
			   <!--<button type="submit" class="btn btn-info btn-fill pull-right">-->
			 
                        </div>
                    </div>

                </div>

app/views/pitches/edit.html.erb
<h1>Editing Pitch</h1>

<%= render 'form' %>

<%= link_to 'Show', @pitch %> |
<%= link_to 'Back', pitches_path %>

app/views/pitches/new.html.erb
<h1>New Pitch</h1>

<%= render 'form' %>

<%= link_to 'Back', pitches_path %>

app/views/pitches/show.html.erb
<p id="notice"><%= notice %></p>

<p class="form-control">
  <strong>Pitch Date:</strong>
  <%= @pitch.pitch_date %>
</p>

<p class="form-control">
  <strong>Author:</strong>
  <%= @pitch.author %>
</p>

<p class="form-control">
  <strong>Company name:</strong>
  <%= @pitch.company_name %>
</p>

<p class="form-control">
  <strong>Sector name:</strong>
  <%= @pitch.sector_name %>
</p>

<p class="form-control">
  <strong>Subsector name:</strong>
  <%= @pitch.subsector_name %>
</p>

<p class="form-control">
  <strong>Download</strong>
  <%= link_to "File", @pitch.document_url %>
  
</p>

<%= link_to 'Edit', edit_pitch_path(@pitch) %> 
<%= link_to 'Back', pitches_path %>

app/views/sectors/edit.html.erb
<h1>Editing Sector</h1>

<%= render 'form' %>

<%= link_to 'Show', @sector %> |
<%= link_to 'Back', sectors_path %>

app/views/sectors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sectors</h1>
<div class="row">
<table class="table">
  <!--
  <thead>
    <tr>
      <th>Sector name</th>
      <th>Sector analysis</th>
      <th>Subsector name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
-->

    
    
  
  <div class="col-md-4">
    <% @sectors.each do |sector| %>
      <div class="thumbnail">    
        <div class="row">
        <div class="col-md-12">Sector Name:<%= link_to sector.sector_name, sector %></div>
        <div class="col-md-12">Sector Analysis:<%= truncate(sector.sector_analysis) %></div>
        <div class="col-md-12">Subsector Name:<%= sector.subsector_name %></div>
        <div class="col-md-12"><%= link_to 'Show', sector %></div>
        <div class="col-md-12"><%= link_to 'Edit', edit_sector_path(sector) %></div>
        <div class="col-md-12"><%= link_to 'Destroy', sector, method: :delete, data: { confirm: 'Are you sure?' } %></div>
</div>
</div>
   <% end %>
  </div>
 
</table>
</div>
<br>

<%= link_to 'New Sector', new_sector_path %>

app/views/sectors/new.html.erb
<h1>New Sector</h1>

<%= render 'form' %>

<%= link_to 'Back', sectors_path %>

app/views/sectors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sector name:</strong>
  <%= @sector.sector_name %>
</p>

<p>
  <strong>Sector analysis:</strong>
  <%= @sector.sector_analysis %>
</p>

<p>
  <strong>Subsector name:</strong>
  <%= @sector.subsector_name %>
</p>

<%= link_to 'Edit', edit_sector_path(@sector) %> |
<%= link_to 'Back', sectors_path %>